#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
readonly NIX_VERSION="2.3.8"
readonly NIX_HOST="releases.nixos.org"
readonly NIX_INSTALLER_URL="https://${NIX_HOST}/nix/nix-${NIX_VERSION}/install"
readonly NIX_INSTALLER_FLAGS=(
  --darwin-use-unencrypted-nix-store-volume
)
readonly NIXPKGS_VERSION="20.09"

bash <(curl -L "${NIX_INSTALLER_URL}") "${NIX_INSTALLER_FLAGS[@]}" 

source "${HOME}/.nix-profile/etc/profile.d/nix.sh"

nix-channel --remove nixpkgs
nix-channel --add "https://nixos.org/channels/nixpkgs-${NIXPKGS_VERSION}-darwin" nixpkgs
nix-channel --add "https://github.com/nix-community/home-manager/archive/release-${NIXPKGS_VERSION}.tar.gz" home-manager
nix-channel --update

nix-shell '<home-manager>' -A install

cp -R "${DIR}/home-manager"/* "${HOME}/.config/nixpkgs/"

home-manager switch


